# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: Copyright (c) 2026 The University of Chicago.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Build a unified normalization Zarr store from PanguWeather-style mean/std NetCDFs.

The ai-rossby normalization schema (PLASIM / ERA5 / E3SM share it):

* Coords: ``sigma_level`` (sigma-coordinate vars), ``pressure_level`` (Pa).
  Variables that exist on just one of the two level systems carry only the
  relevant coord; scalar (surface) variables have no level dim.
* Data variables: one per source channel (e.g. ``ta``, ``zg``, ``tas``). Each
  has a leading ``stat`` axis of length 2 (``"mean"``, ``"std"``).
* Attrs: ``schema_version``, ``source_mean``, ``source_std``,
  ``source_year_range`` (parsed from filename), ``coord_convention``.

The tendency (delta) std for ``predict_delta`` training is **not** included —
it depends on the model timedelta and lives in a separate store generated by
``tools/data/plasim/compute_delta_stats.py``.

The function below is pure and reusable across PLASIM / ERA5 / E3SM converters:
each per-dataset CLI just supplies the source NetCDF paths and the source-coord
names (e.g. ``"Z_2"``/``"Z"`` for PLASIM, ``"Z"`` only for ERA5, etc.).
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Optional

import numpy as np
import xarray as xr

logger = logging.getLogger(__name__)


NORMALIZATION_SCHEMA_VERSION = "1.0"
STAT_NAMES = ("mean", "std")


def _parse_year_range(path: Path) -> Optional[str]:
    """Parse a ``YYYY-YYYY`` (or ``Y-YYYY``, etc.) substring from a file name.

    Used purely for store attrs (provenance). Returns ``None`` if no match.
    """
    m = re.search(r"(\d+)-(\d+)", path.stem)
    return f"{m.group(1)}-{m.group(2)}" if m else None


def _level_coord_for_source(
    ds: xr.Dataset, source_name: str, target_name: str
) -> Optional[np.ndarray]:
    """Look up ``source_name`` as a coord in ``ds`` and return its values.

    ``target_name`` is the ai-rossby coord name we'll write under (used only for
    the warning message). Returns ``None`` if the source ds has no such coord
    (signal that the dataset has no vars on this level system).
    """
    if source_name in ds.coords:
        return ds.coords[source_name].values.astype("float32")
    return None


def build_normalization_dataset(
    mean_ds: xr.Dataset,
    std_ds: xr.Dataset,
    *,
    sigma_coord_name: Optional[str] = "Z_2",
    pressure_coord_name: Optional[str] = "Z",
) -> xr.Dataset:
    """Merge a (mean, std) pair of source NetCDFs into the unified Zarr layout.

    Parameters
    ----------
    mean_ds, std_ds : xarray.Dataset
        Source NetCDFs. Must carry the same set of data variables and the same
        per-variable dim layout (scalar, or one of the configured level dims).
    sigma_coord_name : str or None, optional
        Name of the sigma-level coord in the source files (``"Z_2"`` for PLASIM).
        Pass ``None`` if the dataset has no sigma-coord vars (e.g. ERA5).
    pressure_coord_name : str or None, optional
        Name of the pressure-level coord in the source files (``"Z"`` for PLASIM
        and ERA5). Pass ``None`` if the dataset has no pressure-coord vars.

    Returns
    -------
    xarray.Dataset
        Per-variable arrays of shape ``(stat[, sigma_level | pressure_level])``
        ready to write via :func:`xarray.Dataset.to_zarr`.

    Raises
    ------
    ValueError
        If ``mean_ds`` and ``std_ds`` have mismatched variable sets, or a
        variable's source dims include a coord that's not declared in
        ``sigma_coord_name`` / ``pressure_coord_name``.
    """
    mean_vars = set(mean_ds.data_vars)
    std_vars = set(std_ds.data_vars)
    if mean_vars != std_vars:
        missing_in_std = mean_vars - std_vars
        missing_in_mean = std_vars - mean_vars
        raise ValueError(
            f"mean/std variable sets differ: "
            f"only in mean = {sorted(missing_in_std)}, "
            f"only in std = {sorted(missing_in_mean)}"
        )

    sigma_levels = (
        _level_coord_for_source(mean_ds, sigma_coord_name, "sigma_level")
        if sigma_coord_name is not None
        else None
    )
    pressure_levels = (
        _level_coord_for_source(mean_ds, pressure_coord_name, "pressure_level")
        if pressure_coord_name is not None
        else None
    )

    out_coords: dict = {"stat": list(STAT_NAMES)}
    if sigma_levels is not None:
        out_coords["sigma_level"] = sigma_levels
    if pressure_levels is not None:
        out_coords["pressure_level"] = pressure_levels

    out_vars: dict = {}
    for name in sorted(mean_vars):
        m = mean_ds[name]
        s = std_ds[name]
        if m.dims != s.dims:
            raise ValueError(
                f"variable {name!r}: mean dims {m.dims} != std dims {s.dims}"
            )

        # Decide the target dims based on the source dim.
        if m.ndim == 0:
            target_dims = ("stat",)
        elif m.ndim == 1:
            src_dim = m.dims[0]
            if src_dim == sigma_coord_name:
                target_dims = ("stat", "sigma_level")
            elif src_dim == pressure_coord_name:
                target_dims = ("stat", "pressure_level")
            else:
                raise ValueError(
                    f"variable {name!r}: source dim {src_dim!r} not in "
                    f"({sigma_coord_name!r}, {pressure_coord_name!r}); "
                    "either pass a different sigma_coord_name / pressure_coord_name "
                    "or extend build_normalization_dataset to handle additional dims."
                )
        else:
            raise ValueError(
                f"variable {name!r}: source has {m.ndim} dims (expected 0 or 1)"
            )

        m_arr = np.asarray(m.values, dtype="float32").reshape(-1)
        s_arr = np.asarray(s.values, dtype="float32").reshape(-1)
        stacked = np.stack([m_arr, s_arr], axis=0)
        # Restore the (stat, [level]) shape: scalar vars need a final squeeze.
        if target_dims == ("stat",):
            stacked = stacked.reshape(2)
        out_vars[name] = xr.DataArray(
            stacked.astype("float32"),
            dims=target_dims,
        )

    return xr.Dataset(out_vars, coords=out_coords)


def write_normalization_zarr(
    out_ds: xr.Dataset,
    output_path: str | Path,
    *,
    source_mean: Path,
    source_std: Path,
    coord_convention: str = "ai_rossby_v1",
    overwrite: bool = False,
) -> None:
    """Write a normalization Zarr store at ``output_path`` with provenance attrs.

    Sets ``schema_version``, ``source_mean``, ``source_std``,
    ``source_year_range`` (parsed from the source-mean filename), and
    ``coord_convention``.
    """
    output_path = Path(output_path)
    if output_path.exists() and not overwrite:
        raise FileExistsError(
            f"output path {output_path} exists; pass overwrite=True to replace"
        )

    out_ds = out_ds.assign_attrs(
        normalization_schema_version=NORMALIZATION_SCHEMA_VERSION,
        source_mean=str(source_mean),
        source_std=str(source_std),
        source_year_range=_parse_year_range(source_mean) or "",
        coord_convention=coord_convention,
    )
    mode = "w" if overwrite else "w-"
    out_ds.to_zarr(output_path, mode=mode, consolidated=True, zarr_format=3)
    logger.info(
        "wrote normalization Zarr to %s (vars=%d, sigma_levels=%d, pressure_levels=%d)",
        output_path,
        len(out_ds.data_vars),
        out_ds.coords.get("sigma_level", xr.DataArray([])).size,
        out_ds.coords.get("pressure_level", xr.DataArray([])).size,
    )
