base: &BASE
  paths: &BASE_PATHS
    forecast_path: "/glade/derecho/scratch/aasche/PLASIM/data/ensemble_test/paper/climatology_forecast_everydayinit.zarr"
    obs_path: "/glade/derecho/scratch/aasche/PLASIM/data/ensemble_test/paper/data_11_all_levels.zarr"
    climatology_path: "/glade/derecho/scratch/aasche/PLASIM/data/ensemble_test/paper/climatology_all_levels.zarr"
    output_dir: "/glade/derecho/scratch/aasche/PLASIM/results/paper"
  
  output_name: "climatology_global_mean_MSE_tas_zg"

  variables: ["tas", "zg"]
  # levels: [20000, 50000, 85000]
  levels: [50000]
  time_start: "2011-01-01"
  time_end: "2011-11-30"

  region_file: "/glade/u/home/aasche/PanguWeather/v2.0/regions.json"
  # regions: ["PNW", "France", "Chicago"]
  regions: ["global"]

  persistence: false
  metrics: [EnsembleMeanMSE]
  quantile: 0.99


per: &PER
  <<: *BASE
  output_name: "persistence_JJA_tas_deterministic"
  metrics: [MSE, ACC]
  time_start: "2011-06-01"
  time_end: "2011-08-31"
  regions: ["PNW", "France", "Chicago"]
  variables: ["tas"]
  persistence: true
  paths:
    <<: *BASE_PATHS
    forecast_path: "/glade/derecho/scratch/aasche/PLASIM/data/ensemble_test/paper/one.zarr"

clim: &CLIM
  <<: *BASE
  output_name: "climatology_global_ACC_tas_zg_ua_hus"

single: &SINGLE
  <<: *BASE
  output_name: "single_global_ACC_tas_zg_ua_hus"
  # paths:
  #   <<: *BASE_PATHS
  #   forecast_path: "/glade/derecho/scratch/aasche/PLASIM/data/ensemble_test/paper/one.zarr"

persist: &PERSIST
  <<: *BASE
  output_name: "persistence_global_ACC_tas_zg_ua_hus"
  persistence: true
  # paths:
  #   <<: *BASE_PATHS
  #   forecast_path: "/glade/derecho/scratch/aasche/PLASIM/data/ensemble_test/paper/one.zarr"

mean: &MEAN
  <<: *BASE
  output_name: "mean_global_ACC_tas_zg_ua_hus"
  paths:
    <<: *BASE_PATHS
    forecast_path: "/glade/derecho/scratch/aasche/PLASIM/data/ensemble_test/paper/mean.zarr"

hus: &HUS
  <<: *BASE
  output_name: "ens50_global_hus_crps"
  variables: ["hus"]
  levels: [85000]

ta: &TA
  <<: *BASE
  output_name: "Gaussian_100_global_MSE_ta"
  variables: ["ta"]

ua: &UA
  <<: *BASE
  output_name: "ens50_global_ua_crps"
  variables: ["ua"]
  levels: [20000]

va: &VA
  <<: *BASE
  output_name: "Gaussian_100_global_MSE_va"
  variables: ["va"]

zg: &ZG
  <<: *BASE
  output_name: "ens50_global_zg_crps"
  variables: ["zg"]
  levels: [50000]

pl: &PL
  <<: *BASE
  output_name: "Gaussian_100_global_MSE_pl"
  variables: ["pl"]

pr_6h: &PR
  <<: *BASE
  output_name: "Gaussian_100_global_MSE_pr_6h"
  variables: ["pr_6h"]

tas: &TAS
  <<: *BASE
  output_name: "ens50_global_tas_crps"
  variables: ["tas"]

chicago: &CHICAGO
  <<: *BASE
  regions: ["Chicago"]
  output_name: "brier_99_ens100avg_unbiased_Chicago"

france: &FRANCE
  <<: *BASE
  regions: ["France"]
  output_name: "brier_99_ens100avg_unbiased_France"

pnw: &PNW
  <<: *BASE
  regions: ["PNW"]
  output_name: "brier_99_ens100avg_unbiased_PNW"