model:
    model_name: Decoder_CNN
    lr: 5.0e-5
    level_weight: cosine
    surface_weight: null
    multi_level_weight: [1.0, 1.0, 1.0, 5.0, 1.0]
    diag_weight: null
    spectral_loss_weight: 0.10
    spectral_z_weight: 1.0
    Decoder_CNN:
        encoder:
            downsample_factor: 4
        decoder:
            out_channels: 151  # 6 + 26*9 + 9 = 249
            hidden_channels: 512
            z_channels: 151
            num_out_blocks: 2
            num_res_blocks: 3
            use_history: False
data:
    data_dir: '/glade/derecho/scratch/awikner/ERA5/h5'
    upper_air_variables: ["temperature",
                  "u_component_of_wind",
                  "v_component_of_wind",
                  "geopotential",
                  "specific_total_water"]
    surface_variables: ["skin_temperature",
                     "surface_pressure",
                     "2m_temperature",
                     "2m_specific_humidity", 
                     "10m_u_component_of_wind", 
                     "10m_v_component_of_wind"]
    diagnostic_variables: ["USWRFtoa_24h",
                        "ULWRFtoa_24h", 
                       "USWRFsfc_24h",
                       "ULWRFsfc_24h",
                       "DSWRFsfc_24h",
                       "DLWRFsfc_24h",
                       "LHTFLsfc_24h",
                       "SHTFLsfc_24h",
                       "PRATEsfc_24h", 
                       "hcc_24h",
                       "lcc_24h", 
                       "mcc_24h", 
                       "mn2t_24h", 
                       "mx2t_24h", 
                       "mxtpr_24h"]
    constant_boundary_variables: ["geopotential_at_surface", 
                                    "land_sea_mask"]
    varying_boundary_variables: ["DSWRFtoa", 
                                "global_mean_co2",
                                "sea_surface_temperature", # has nans
                                "sea_ice_cover"] # has nans
    mask_fill: {'sea_surface_temperature': 270.,
                'sea_ice_cover': 0.}
    train_year_start: 1979
    train_year_end: 2012
    val_year_start: 2012
    val_year_end: 2013
    mean_path: "/glade/derecho/scratch/ayz/ERA5/h5/normalize_mean.nc"
    std_path: "/glade/derecho/scratch/ayz/ERA5/h5/normalize_std.nc"
    forecast_lead_times: [1] 
    autoencoder: True
    use_history: False

    calendar: 'standard'
    data_timedelta_hours: 6
    timedelta_hours: 24
    has_year_zero: False
    levels: [5, 7, 10, 20, 30, 50, 70, 100, 125, 150, 175, 200, 250, 300, 400, 500, 600, 700, 800, 850, 875, 900, 925, 950, 975, 1000]
    horizontal_resolution: [180, 360]
    predict_delta: False
    epsilon_factor: 0
    val_num_inferences: 0 # use entire val set
    diagnostic_input: True # specific to AE model, we need diagnostic at time t, since we are training a downscaler

    batch_size: 1
    num_data_workers: 8 

training:
    seed: 42
    devices: 4
    accelerator: gpu
    strategy: ddp
    precision: 32-true
    check_val_every_n_epoch: 1
    log_every_n_steps: 10
    max_epochs: 50
    ema_decay: 0.99
    num_sanity_val_steps: 1
    log_dir: /glade/derecho/scratch/ayz/AMIP_logs/
    project: amip
    wandb_mode: online
    checkpoint: /glade/derecho/scratch/ayz/AMIP_logs/Decoder_CNN_CNN_42_2026-03-31T12-17-51/last.ckpt
    description: CNN
    accumulate_grad_batches: 16
    optimizer: adam
    plot_val: True
