model:
    model_name: AE_ClimaDiT
    lr: 5.0e-5
    AE_ClimaDiT:
        encoder:
            downsample_factor: 4
        decoder:
            in_dim: 249
            out_dim: 249
            dim: 256
            num_heads: 16
            num_blocks: 24
            num_out_blocks: 8

data:
    train_data_path: /glade/derecho/scratch/ayz/AMIP_train_new.h5
    val_data_path: /glade/derecho/scratch/ayz/AMIP_valid_new.h5
    norm_stats_path: /glade/derecho/scratch/ayz/norm_stats_dict_new.pkl
        
    training_nsteps: 2
    val_nsteps: 2
    val_horizon: 1460 # 1 year
    use_climatology: False

    batch_size: 1
    num_workers: 4

training:
    seed: 42
    devices: 4
    accelerator: gpu
    strategy: ddp_find_unused_parameters_true
    precision: 32-true #16-mixed
    check_val_every_n_epoch: 1
    log_every_n_steps: 10
    max_epochs: 50
    ema_decay: 0.99
    num_sanity_val_steps: 1
    log_dir: /glade/derecho/scratch/ayz/AMIP_logs/
    project: amip
    wandb_mode: online
    checkpoint: null
    description: AE_ClimaDiT
    accumulate_grad_batches: 16