model:
    model_name: AE_simple
    lr: 5.0e-5
    separate_diagnostic: True
    AE_simple:
        encoder:
            in_channels: 136  # 6 + 26*9 + 9 = 249
            hidden_channels: 384
            z_channels: 136
            downsample_type: dc
        decoder:
            out_channels: 249  # 6 + 26*9 + 9 = 249
            hidden_channels: 384
            z_channels: 136
            upsample_type: dc
data:
    train_data_path: /glade/derecho/scratch/ayz/AMIP_train_new.h5
    val_data_path: /glade/derecho/scratch/ayz/AMIP_valid_new.h5
    norm_stats_path: /glade/derecho/scratch/ayz/norm_stats_dict_new.pkl
        
    training_nsteps: 1
    val_nsteps: 1
    val_horizon: 1460 # 1 year
    use_climatology: False
    downsample_levels: 1

    batch_size: 1
    num_workers: 4

training:
    seed: 42
    devices: 4
    accelerator: gpu
    strategy: ddp
    precision: 32-true #16-mixed
    check_val_every_n_epoch: 1
    log_every_n_steps: 10
    max_epochs: 50
    ema_decay: 0.99
    num_sanity_val_steps: 1
    log_dir: /glade/derecho/scratch/ayz/AMIP_logs/
    project: amip
    wandb_mode: online
    checkpoint: null
    description: d16_simple_DC_diag
    accumulate_grad_batches: 16