### base config ###
base_config: &BASE
  loss: 'weightedl1'
  lr: 0.0001
  weight_decay: 3e-6
  scheduler: 'OneCycleLR' #'ReduceLROnPlateau'
  num_data_workers: 8
  oc_pct_start: 0.1
  oc_div_factor: 1e5
  oc_final_div_factor: 0.00025
  
  log_to_screen: !!bool True
  log_to_wandb: !!bool True
  save_checkpoint: !!bool True

  optimizer_type: 'Adam' #'FusedAdam'

  plot_animations: !!bool False

  nettype: 'pangu_plasim'
  group: 'alex-optim'

  exp_dir: 'results'

  enable_fp8: False
  fresh_start: True
  use_transformer_engine: False
  early_stopping: False

  project: 'Pangu-PLASIM'
  name: 'PLASIM-S2S'



PLASIM: &PLASIM
  <<: *BASE
  #data_dir: '/scratch/midway2/awikner/PLASIM/train_val_test_data_res'
  #boundary_dir: 'boundary_vars'
  upper_air_variables: ['temperature', 'u_component_of_wind', 'v_component_of_wind',
                        'specific_humidity', 'geopotential']
  surface_variables: ['2m_temperature', '10m_u_component_of_wind', '10m_v_component_of_wind',
                      'mean_sea_level_pressure', 'surface_pressure']
  diagnostic_variables: ['total_precipitation_24hr', 'mean_top_net_long_wave_radiation_flux', 
                         'minimum_2m_temperature_since_previous_post_processing',
                         'maximum_2m_temperature_since_previous_post_processing']
  land_variables: ['volumetric_soil_water_layer_1', 'soil_temperature_level_1', 'skin_temperature']
  ocean_variables: ['sea_surface_temperature']
  mask_output: False
  constant_boundary_variables: ['land_sea_mask', 'geopotential_at_surface']
  varying_boundary_variables: ['toa_incident_solar_radiation', 'snow_depth', 'sea_ice_cover']
  train_year_start: 1979
  train_year_end: 2019
  val_year_start: 2019
  val_year_end: 2020
  #surface_mean: 'data_12-111_surface_mean.nc'
  #surface_std: 'data_12-111_pr_12h_mrso_res_std.py'
  #surface_ff_std: 'plasim_pr_12h_51_150_surface_std.nc'
  #upper_air_mean: 'data_12-111_mean_Z.nc'
  #upper_air_std: 'data_12-111_pr_12h_mrso_res_std.py'
  #upper_air_ff_std: 'plasim_pr_12h_51_150_std.nc'
  #boundary_mean: 'plasim_test_51_150_boundary_mean.nc'
  #boundary_std: 'plasim_test_51_150_boundary_std.nc'
  #diagnostic_mean: 'data_12-111_surface_mean.nc'
  #diagnostic_std: 'data_12-111_surface_std.nc'
  #surface_delta_std: 'data_12-111_surface_delta_std.nc'
  #upper_air_delta_std: 'data_12-111_delta_std_Z.nc'
  calendar: 'gregorian'
  timedelta_hours: 24
  batch_size: 64
  max_epochs: 100

  has_year_zero: False

  num_levels: 17
  #num_levels: 10
  #levels: [5000., 10000., 20000., 25000., 40000., 50000., 70000., 85000., 92500., 100000.]
  levels: []
  horizontal_resolution: [180, 380]
  depths: [2, 6, 6, 2]
  predict_delta: False
  patch_size: [2, 2, 2]
  updown_scale_factor: 2
  window_size: [2, 6, 12]
  epsilon_factor: 0
  upper_air_boundary: False
  subpixel_deconv: True
  recovery_head: True
  diagnostic_head: False
  vertical_windowing: False
  train_year_to_year: False

  diagnostic_logs: False
  forecast_lead_times: [1]

  lev: 'plev'
  num_inferences: 100

  use_reentrant: False
  checkpointing: 3
  #use_ff_input: False

modified_1: &MODIFIED
  <<: *BASE
  lr: 5E-4
  batch_size: 16 
  max_epochs: 80 
  scheduler: 'CosineAnnealingLR'
  optimizer_type: 'FusedAdam'
