### base config ###
base_config: &BASE
  loss: 'l1'
  lr: 2.5E-4
  weight_decay: 3e-6
  scheduler: 'CosineAnnealingLR' #'ReduceLROnPlateau', #'CosineAnnealingLR', #'OneCycleLR'
  num_data_workers: 8
  
  log_to_screen: !!bool True
  log_to_wandb: !!bool False
  diagnostic_logs: False
  save_checkpoint: !!bool False

  optimizer_type: 'Adam' #'FusedAdam', #'Adam'

  plot_animations: !!bool False

  nettype: 'pangu_plasim'

  exp_dir: 'results'

  # Add this line to enable/disable Transformer Engine
  use_transformer_engine: !!bool True
  enable_fp8: !!bool False



PLASIM: &PLASIM
  <<: *BASE
  data_dir: '/scratch/midway2/awikner/PLASIM/data/train_val_test_data'
  boundary_dir: 'boundary_vars'
  upper_air_variables: ['ta', 'ua', 'va', 'hus', 'clw']
  surface_variables: ['pl', 'tas']
  constant_boundary_variables: ['lsm', 'z0', 'sg']
  varying_boundary_variables: ['sst', 'rsdt', 'sic']
  train_year_start: 100
  train_year_end: 104
  val_year_start: 104
  val_year_end: 105
  surface_mean: 'plasim_test_51_150_surface_mean.nc'
  surface_std: 'plasim_test_51_150_surface_std.nc'
  upper_air_mean: 'plasim_test_51_150_mean.nc'
  upper_air_std: 'plasim_test_51_150_std.nc'
  boundary_mean: 'plasim_test_51_150_boundary_mean.nc'
  boundary_std: 'plasim_test_51_150_boundary_std.nc'
  calendar: 'proleptic_gregorian'
  timedelta_hours: 6
  batch_size: 32
  max_epochs: 6

  has_year_zero: False

  num_levels: 10
  horizontal_resolution: [64, 128]
  depths: [2, 6, 6, 2]
  predict_delta: False
  patch_size: [2, 2, 2]
  updown_scale_factor: 2

  inference_steps: 0



  


modified_1: &MODIFIED
  <<: *BASE
  lr: 5E-4
  batch_size: 16 
  max_epochs: 80 
  scheduler: 'CosineAnnealingLR'
  optimizer_type: 'FusedAdam'


