### base config ###
base_config: &BASE
  loss: 'weightedl1'
  lr: 0.0001
  weight_decay: 3e-6
  scheduler: 'OneCycleLR' #'ReduceLROnPlateau'
  num_data_workers: 8
  oc_pct_start: 0.1
  oc_div_factor: 1e5
  oc_final_div_factor: 0.00025
  
  log_to_screen: !!bool True
  log_to_wandb: !!bool True
  save_checkpoint: !!bool True

  optimizer_type: 'Adam' #'FusedAdam'

  plot_animations: !!bool False

  nettype: 'pangu_plasim'
  group: 's2s-dev'

  exp_dir: 'results'

  enable_fp8: False
  fresh_start: False
  use_transformer_engine: False
  early_stopping: False

  project: 'Pangu-S2S'
  name: 'S2S'



S2S: &S2S
  <<: *BASE
  data_dir: '/net/scratch2/awikner/pangu_s2s/val'
  upper_air_variables: ['temperature', 'u_component_of_wind', 'v_component_of_wind',
                        'specific_humidity', 'geopotential']
  surface_variables: ['2m_temperature', '10m_u_component_of_wind', '10m_v_component_of_wind',
                      'mean_sea_level_pressure', 'surface_pressure']
  diagnostic_variables: ['total_precipitation_24hr', 'mean_top_net_long_wave_radiation_flux', 
                         'minimum_2m_temperature_since_previous_post_processing',
                         'maximum_2m_temperature_since_previous_post_processing']
  land_variables: ['volumetric_soil_water_layer_1', 'soil_temperature_level_1', 'skin_temperature']
  ocean_variables: ['sea_surface_temperature']
  constant_boundary_variables: ['land_sea_mask', 'geopotential_at_surface']
  varying_boundary_variables: ['toa_incident_solar_radiation', 'snow_depth', 'sea_ice_cover']
  mask_fill: {'volumetric_soil_water_layer_1': 0.,
              'soil_temperature_level_1': 270.,
              'skin_temperature': 270.,
              'sea_surface_temperature': 270.,
              'sea_ice_cover': 0.}
  mask_output: False
  train_year_start: 2017
  train_year_end: 2018
  val_year_start: 2018
  val_year_end: 2019
  data_timedelta_hours: 6
  surface_mean: 'pangu_s2s_1979-2018_surface_mean.nc'
  surface_std: 'pangu_s2s_1979-2018_surface_std.nc'
  surface_ff_std: 'pangu_s2s_1979-2018_surface_std.nc'
  upper_air_mean: 'pangu_s2s_1979-2018_mean.nc'
  upper_air_std: 'pangu_s2s_1979-2018_std.nc'
  upper_air_ff_std: 'pangu_s2s_1979-2018_std.nc'
  boundary_mean: 'pangu_s2s_1979-2018_surface_mean.nc'
  boundary_std: 'pangu_s2s_1979-2018_surface_std.nc'
  diagnostic_mean: 'pangu_s2s_1979-2018_surface_mean.nc'
  diagnostic_std: 'pangu_s2s_1979-2018_surface_std.nc'
  #surface_delta_std: 'data_12-111_surface_delta_std.nc'
  #upper_air_delta_std: 'data_12-111_delta_std_Z.nc'
  calendar: 'standard'
  timedelta_hours: 24
  batch_size: 8
  max_epochs: 100

  has_year_zero: False

  num_levels: 17
  #num_levels: 10
  levels: [5, 10, 20, 30, 50, 70, 100, 150, 250, 300, 400, 500, 600, 700, 850, 925, 1000]
  horizontal_resolution: [180, 360]
  depths: [2, 6, 6, 2]
  predict_delta: False
  patch_size: [2, 4, 4]
  updown_scale_factor: 2
  window_size: [2, 6, 12]
  epsilon_factor: 0
  upper_air_boundary: False
  subpixel_deconv: True
  recovery_head: True
  diagnostic_head: False
  vertical_windowing: True
  train_year_to_year: False

  diagnostic_logs: False
  forecast_lead_times: [1]

  lev: 'plev'
  num_inferences: 100

  use_reentrant: False
  checkpointing: 3
  lat: [-89.5, -88.5, -87.5, -86.5, -85.5, -84.5, -83.5, -82.5, -81.5, -80.5, 
    -79.5, -78.5, -77.5, -76.5, -75.5, -74.5, -73.5, -72.5, -71.5, -70.5, 
    -69.5, -68.5, -67.5, -66.5, -65.5, -64.5, -63.5, -62.5, -61.5, -60.5, 
    -59.5, -58.5, -57.5, -56.5, -55.5, -54.5, -53.5, -52.5, -51.5, -50.5, 
    -49.5, -48.5, -47.5, -46.5, -45.5, -44.5, -43.5, -42.5, -41.5, -40.5, 
    -39.5, -38.5, -37.5, -36.5, -35.5, -34.5, -33.5, -32.5, -31.5, -30.5, 
    -29.5, -28.5, -27.5, -26.5, -25.5, -24.5, -23.5, -22.5, -21.5, -20.5, 
    -19.5, -18.5, -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5, 
    -9.5, -8.5, -7.5, -6.5, -5.5, -4.5, -3.5, -2.5, -1.5, -0.5, 0.5, 1.5, 
    2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 
    15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5, 
    27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 
    39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 
    51.5, 52.5, 53.5, 54.5, 55.5, 56.5, 57.5, 58.5, 59.5, 60.5, 61.5, 62.5, 
    63.5, 64.5, 65.5, 66.5, 67.5, 68.5, 69.5, 70.5, 71.5, 72.5, 73.5, 74.5, 
    75.5, 76.5, 77.5, 78.5, 79.5, 80.5, 81.5, 82.5, 83.5, 84.5, 85.5, 86.5, 
    87.5, 88.5, 89.5]
  #use_ff_input: False

modified_1: &MODIFIED
  <<: *BASE
  lr: 5E-4
  batch_size: 16 
  max_epochs: 80 
  scheduler: 'CosineAnnealingLR'
  optimizer_type: 'FusedAdam'
