### base config ###
base_config: &BASE
  loss: %LOSS%
  lr: %LR%
  weight_decay: 3e-6
  scheduler: 'CosineAnnealingLR' #'ReduceLROnPlateau'
  num_data_workers: 16
  
  log_to_screen: !!bool True
  log_to_wandb: !!bool True
  save_checkpoint: !!bool True

  optimizer_type: 'Adam' #'FusedAdam'

  plot_animations: !!bool False

  nettype: 'pangu_plasim'

  exp_dir: 'results'



PLASIM: &PLASIM
  <<: *BASE
  data_dir: '/scratch/user/u.aw164890/PLASIM/train_val_test_data'
  boundary_dir: 'boundary_vars'
  upper_air_variables: ['ta', 'ua', 'va', 'hus', 'clw']
  surface_variables: ['pl', 'tas']
  constant_boundary_variables: ['lsm', 'z0', 'sg']
  varying_boundary_variables: ['sst', 'rsdt', 'sic']
  train_year_start: 51
  train_year_end: 151
  val_year_start: 151
  val_year_end: 153
  surface_mean: 'plasim_test_51_150_surface_mean.nc'
  surface_std: 'plasim_test_51_150_surface_res_std.nc'
  surface_ff_std: 'plasim_test_51_150_surface_std.nc'
  upper_air_mean: 'plasim_test_51_150_mean.nc'
  upper_air_std: 'plasim_test_51_150_res_std.nc'
  upper_air_ff_std: 'plasim_test_51_150_std.nc'
  boundary_mean: 'plasim_test_51_150_boundary_mean.nc'
  boundary_std: 'plasim_test_51_150_boundary_std.nc'
  calendar: 'proleptic_gregorian'
  timedelta_hours: 6
  batch_size: 64
  max_epochs: 100

  has_year_zero: False

  num_levels: 10
  horizontal_resolution: [64, 128]
  depths: [2, 6, 6, 2]
  predict_delta: False
  patch_size: [2, 2, 2]
  updown_scale_factor: 2
  window_size: %WINDOW_SIZE%
  epsilon_factor: %EPSILON%

  diagnostic_logs: True
  inference_steps: 0



  


modified_1: &MODIFIED
  <<: *BASE
  lr: 5E-4
  batch_size: 16 
  max_epochs: 80 
  scheduler: 'CosineAnnealingLR'
  optimizer_type: 'FusedAdam'


