model:
    model_name: DCAE
    lr: 5.0e-5
    DCAE:
        encoder:
            in_channels: 249 # 6 + 26*9 + 9 = 249
            hidden_channels: [512, 768, 1024] #[256, 512, 512]
            blocks_per_layer: [4, 4, 4] # [4, 4, 4]
            conv_type: '2d'
            saturate: True
        decoder:
            in_channels: 249 # 6 + 26*9 + 9 = 249
            hidden_channels: [1024, 768, 512] #[256, 512, 512]
            blocks_per_layer: [4, 4, 4] #[4, 4, 4]
            conv_type: '2d'
    AE_3D:
        encoder:
            surface_channels: 6
            multilevel_channels: 9
            diagnostic_channels: 9
            nlevels: 26
            hidden_channels: [64, 128, 256]
            blocks_per_layer: [2, 2, 2]
        decoder:
            surface_channels: 6
            multilevel_channels: 9
            diagnostic_channels: 9
            nlevels: 26
            hidden_channels: [256, 128, 64]
            blocks_per_layer: [2, 2, 2]
data:
    train_data_path: /glade/derecho/scratch/ayz/AMIP_train_new.h5
    val_data_path: /glade/derecho/scratch/ayz/AMIP_valid_new.h5
    norm_stats_path: /glade/derecho/scratch/ayz/norm_stats_dict_new.pkl
        
    training_nsteps: 1
    val_nsteps: 1
    val_horizon: 1460 # 1 year
    use_climatology: False

    batch_size: 1
    num_workers: 2

training:
    seed: 42
    devices: 4
    accelerator: gpu
    strategy: ddp
    precision: 32-true #16-mixed
    check_val_every_n_epoch: 1
    log_every_n_steps: 10
    max_epochs: 50
    ema_decay: 0.99
    num_sanity_val_steps: 1
    log_dir: /glade/derecho/scratch/ayz/AMIP_logs/
    project: amip
    wandb_mode: online
    checkpoint: null
    description: d16_Large
    accumulate_grad_batches: 8