burn7.x:	burn7.cpp
	icc -O2 -o burn7.x burn7.cpp -I/ccc/cont003/dsku/blanchet/home/user/enslyon/lepriolc/netcdf-cxx/include -I/ccc/products/netcdf-c-4.6.0/intel--20.0.0__openmpi--4.0.1/hdf5__parallel/include -L/ccc/cont003/dsku/blanchet/home/user/enslyon/lepriolc/netcdf-cxx/lib -lm -lnetcdf_c++ -L/ccc/products/netcdf-c-4.6.0/intel--20.0.0__openmpi--4.0.1/hdf5__parallel/lib -lnetcdf
